[package]
name = "libbladerf-sys"
version = "0.2.0"
authors = ["Jon Lamb"]
edition = "2021"
links = "bladeRF"
build = "build.rs"

[dependencies]
bitfield = "0.17"

[dependencies.serde]
version = "1.0"
features = ["derive"]

[build-dependencies]
bindgen = "0.70"
